"""
Scanner integration using the wtfs binary.

The wtfs binary is bundled with the Python package and automatically
located. This provides full threading support and process isolation.
"""

import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional


def _set_fd_limit_linux():
    """Set high file descriptor limit on Linux (called in child process)."""
    if sys.platform == 'linux':
        try:
            import resource
            # Get current limits
            soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE)
            # Try to set soft limit to hard limit (or 100k, whichever is lower)
            # This doesn't require root and uses the system's configured hard limit
            target = min(hard, 100_000)
            resource.setrlimit(resource.RLIMIT_NOFILE, (target, hard))
        except (ImportError, ValueError, OSError):
            # If we can't set it, that's okay - just use system defaults
            pass


class Scanner:
    """
    Fast directory scanner using the bundled wtfs binary.

    Example:
        from wtfs import Scanner

        scanner = Scanner()
        results = scanner.scan('.')
        print(f"Found {results['directories']} directories")
    """

    def __init__(
        self,
        skip_hidden: bool = False,
        large_file_threshold: int = 100 * 1024 * 1024,  # 100 MB
    ):
        """
        Initialize scanner.

        Args:
            skip_hidden: Whether to skip hidden files/directories
            large_file_threshold: Size threshold for tracking large files (bytes)
        """
        self.skip_hidden = skip_hidden
        self.large_file_threshold = large_file_threshold
        self.wtfs_binary = self._find_binary()

    def _find_binary(self) -> Path:
        """Find the bundled wtfs binary for the current platform."""
        import platform

        package_dir = Path(__file__).parent

        # Determine platform-specific binary name
        system = platform.system().lower()
        machine = platform.machine().lower()

        # Normalize architecture names to match Zig's conventions
        arch_map = {
            'x86_64': 'x86_64',
            'amd64': 'x86_64',
            'arm64': 'aarch64',
            'aarch64': 'aarch64',
        }
        arch = arch_map.get(machine, machine)

        # Platform-specific binary name (as generated by zig build python)
        platform_binary = f"wtfs-{system}-{arch}"

        # Try package _bin directory (for installed wheel)
        bundled = package_dir / '_bin' / platform_binary
        if bundled.exists():
            return bundled

        # Try development zig-out location
        dev_binary = package_dir.parent / 'zig-out' / 'bin' / platform_binary
        if dev_binary.exists():
            return dev_binary

        # Fallback: try plain 'wtfs' in development
        dev_plain = package_dir.parent / 'zig-out' / 'bin' / 'wtfs'
        if dev_plain.exists():
            return dev_plain

        raise RuntimeError(
            f"wtfs binary not found for {system}-{arch}. "
            f"Expected: {platform_binary}\n"
            f"Run 'zig build python' to build all platform binaries."
        )

    def scan(
        self,
        path: str = '.',
        output_file: Optional[str] = None,
        force: bool = False,
    ) -> dict:
        """
        Scan a directory and return results.

        Args:
            path: Directory path to scan
            output_file: Optional path to save binary dump. If None, uses temp file.

        Returns:
            Dictionary with keys: 'directories', 'files', 'bytes', 'dump_file'
        """
        # Create temp file if no output specified
        if output_file is None:
            temp_fd, output_file = tempfile.mkstemp(suffix='.wtfs', prefix='scan-')
            import os
            os.close(temp_fd)  # Close fd, wtfs will overwrite

        dump_path = Path(output_file)

        try:
            # Build command
            cmd = [str(self.wtfs_binary)]

            if not self.skip_hidden:
                pass  # wtfs scans hidden by default
            else:
                cmd.append('--skip-hidden')

            if force:
                cmd.append('--force')

            cmd.extend([
                '--large-file-threshold',
                self._format_size(self.large_file_threshold),
                '--binary-output',
                str(dump_path),
                str(path),
            ])

            # Run wtfs binary with high fd limit on Linux
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
                preexec_fn=_set_fd_limit_linux if sys.platform == 'linux' else None,
            )

            # Load the dump to extract totals
            from . import dump
            data = dump.load(str(dump_path))

            return {
                'directories': data.totals.directories,
                'files': data.totals.files,
                'bytes': data.totals.bytes,
                'dump_file': str(dump_path),
            }

        except subprocess.CalledProcessError as e:
            raise RuntimeError(
                f"wtfs scan failed: {e.stderr}"
            ) from e

    def _format_size(self, size: int) -> str:
        """Format size for wtfs command line."""
        if size >= 1024**4:
            return f"{size // 1024**4}T"
        elif size >= 1024**3:
            return f"{size // 1024**3}G"
        elif size >= 1024**2:
            return f"{size // 1024**2}M"
        elif size >= 1024:
            return f"{size // 1024}K"
        else:
            return str(size)

    def scan_to_file(self, path: str, output_file: str) -> dict:
        """
        Scan a directory and save to a specific output file.

        Args:
            path: Directory path to scan
            output_file: Path to save binary dump

        Returns:
            Dictionary with scan results
        """
        return self.scan(path, output_file)

